name: Home
version: '${version}'
main: io.github.elihuso.home.Home
api-version: '1.16'

commands:
  home:
    permission: home.home
  sethome:
    permission: home.set
    aliases: [ homeset ]
  delhome:
    permission: home.del
    aliases: [ homedel, deletehome, homedelete ]
  listhome:
    permission: home.list
    aliases: [ homelist ]
  bed:
    permission: home.bed

permissions:
  home.home:
    default: true
  home.set:
    default: true
  home.del:
    default: true
  home.list:
    default: true
  home.bed:
    default: true